export const _throw_exception = (msg: string) => {
    throw msg
}